sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t indra0007/docker-react -f Dockerfile.dev .

scripts:
  - docker run indra0007/docker-react npm run test -- --coverage
